### ISSUE TITLE
Issues setting up local development environment

### ISSUE THREAD

**Issue by chrismilson** [keycloak/terraform-provider-keycloak#1133]
### Description

When setting up the local development environment, the instructions indicated the versions of go and terraform that I would require. It didn't mention that Java was also required, and so `make local` failed on the user-federation-example.

### Motivation

It would be nice to have a more streamlined development environment setup, to make it easier for more people to contribute to the project.

**Comment by chrismilson** [comment]
Perhaps this should become a discussion? Any advice would be greatly appreciated.

**Comment by irby** [comment]
Hey Chris,

I think it would be a good idea to call out some of the prerequisites, maybe a `CONTRIBUTING.md` file might be nice.

If neither Make nor Java are installed on your machine, this will at least help you get started:

1. Comment out the custom-user-federation-example volume in `docker-compose.yml`

```yaml
volumes:
  postgres:
services:
  postgres:
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    image: postgres:16
    volumes:
    - postgres:/var/lib/postgresql
  openldap:
    image: bitnami/openldap:2.6
    environment:
      LDAP_PORT_NUMBER: 389
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: --verbose start-dev --features=preview
    depends_on:
    - postgres
    - openldap
    environment:
    - KC_BOOTSTRAP_ADMIN_USERNAME=keycloak
    - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    - KC_LOG_LEVEL=INFO,org.keycloak:debug
    - KC_DB=postgres
    - KC_DB_URL_HOST=postgres
    - KC_DB_URL_PORT=5432
    - KC_DB_URL_DATABASE=keycloak
    - KC_DB_USERNAME=keycloak
    - KC_DB_PASSWORD=password
    - KC_LOG_CONSOLE_COLOR=true
    - KC_FEATURES=preview
    - QUARKUS_HTTP_ACCESS_LOG_ENABLED=true
    - QUARKUS_HTTP_RECORD_REQUEST_START_TIME=true
# Enable for remote java debugging
#    - DEBUG=true
#    - DEBUG_PORT=*:8787
    ports:
    - "8080:8080"
# Enable for remote java debugging
#    - "8787:8787"
    volumes:
# Make the custom-user-federation-example extension available to Keycloak. The :z option is required and tells Docker that the volume content will be shared between containers.
    # - ./custom-user-federation-example/build/libs/custom-user-federation-example-all.jar:/opt/keycloak/providers/custom-user-federation-example-all.jar:z
    - ./provider/misc:/opt/keycloak/misc:z
```

Run the commands inside the `local` block of the makefile in your Terminal:

```shell
docker compose up --build -d
./scripts/wait-for-local-keycloak.sh
./scripts/create-terraform-client.sh
```
